# Change these first
owner: kaerez # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
# If issues are deleted, they won't show up in the incident history.
skipDeleteIssues: true
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: false
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36

sites:
  - name: KSEC
    icon: https://icons.duckduckgo.com/ip3/www.kalman.co.il.ico
    url: www.kalman.co.il
    check: "tcp-ping"
    port: 443
    slug: KSEC
  - name: Google DNS 8.8.8.8
    icon: https://www.google.com/favicon.ico
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    slug: G8888
  - name: Google DNS 8.8.4.4
    icon: https://www.google.com/favicon.ico
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
    slug: G8844
  - name: Google DNS - dns.google
    icon: https://www.google.com/favicon.ico
    url: https://dns.google
    slug: GURI

# - name: POST to Google
#   url: https://www.google.com
#   method: POST
#
# - name: Secret Site
#   url: $SECRET_SITE
#
# - name: API endpoint
#   url: https://example.com/get-user/3?api_key=$MY_API_KEY
#
# - name: API endpoint with data
#   method: POST
#   url: https://example.com/login
#   headers:
#     - "Content-Type: application/json"
#   body: '{ "password": "hello" }'
#
# - name: Google
#     url: https://www.google.com
# assignees can be global and in each check
#     assignees:
#           - AnandChowdhary
#     expectedStatusCodes:
#       - 200
#       - 201
#       - 404
# default is 30 seconds, 5000 = 5 seconds
#    maxResponseTime: 5000
# if http response has File not found then degraded
#    __dangerous__body_degraded: "File not found"
# if http response has File not found then down
#    __dangerous__body_down: "File not found"
# if http response does NOT have status:UP then down
#  __dangerous__body_down_if_text_missing: '"status":"UP"'
# if http response does NOT have status:UP then degraded
#  __dangerous__body_degraded_if_text_missing: '"status":"UP"'
# don't check server cert ca validity
#   __dangerous__disable_verify_peer: true
# don't check server cert name mismatch
#   __dangerous__disable_verify_host: true
# don't check server cert AT ALL (ca / host)
#   __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://icons.duckduckgo.com/ip3/www.kalman.co.il.ico
  favicon: https://icons.duckduckgo.com/ip3/www.kalman.co.il.ico
  # favicon: https://example.com/favicon.png
  # faviconSvg: https://example.com/logo.svg
  # customHeadHtml: "<!-- Custom HTML to add in the <head> tag -->"
  # customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"
  # customFootHtml: "<!-- Custom HTML to add at the end of <body> -->"
  # external js
  # scripts:
  #   - src: https://example.com/script.js
  #   - src: https://example.com/script-2.js
  #     async: true
  # internal js
  # js: "window.onload = function() { alert('Hello!') }"
  # By default, Upptime uses https://raw.githubusercontent.com to fetch raw content from GitHub repositories. If you are using a proxy or another content delivery URL, you can replace the default user content base URL.
  # userContentBaseUrl: https://raw.githubusercontent.com
  #links:
  #  - rel: stylesheet
  #    href: https://example.com/custom-styles.css
  #css: "body { opacity: 0.5 }"
  metaTags:
  #  - name: "color-scheme"
  #    content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"

  name: KSEC Status Monitor
  introTitle: "**Status Details**"
  introMessage: "**View Current and Past Status**"
  theme: light #light, dark, night or ocean
  # navbar:
  #   - title: aaa
  #     href: /
  commitMessages:
    commitAuthorName: "KSEC Bot"
    commitAuthorEmail: "ksecbot@kalman.co.il"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
    footer: KSEC Status Monitor
